services:
  - type: web
    name: nexus-dashboard-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://training-project-full-stack.vercel.app
    healthCheckPath: /
